"""GEDCOM Bridge — Feature #15.

Two endpoints:

  GET  /api/gedcom/{cs}   — emit a GEDCOM 5.5.1 .ged for a callsign/holder:
                             RESI events per edition-year address,
                             custom events for first-license / upgrades /
                             callsign-changes, per-fact SOUR citing the edition.
                             Returns text/plain with Content-Disposition .ged.

  POST /api/gedcom/scan   — upload a family-tree GEDCOM (max 5 MB, stateless,
                             never stored).  Parse INDI names, match against the
                             pre-built phonetic_index.json + state/era
                             plausibility.  Return conservative candidate hits
                             with confidence and explicit 'verify yourself'
                             framing.

GEDCOM 5.5.1 is a line-based text format:
    level TAG [value]
Lines are at most 255 chars; continuations use CONT.
"""

from __future__ import annotations

import io
import logging
import re
import sqlite3
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Path as PathParam, UploadFile, File
from fastapi.responses import Response
from pydantic import BaseModel

from app.db import get_db
from app.routes.callsign import normalize_callsign
from app.integrations import phonetic_index as _phonetic_index

logger = logging.getLogger("callbook.backend.gedcom")

router = APIRouter(prefix="/api/gedcom", tags=["gedcom"])

_GEDCOM_MAX_BYTES = 5 * 1024 * 1024  # 5 MB

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class GedcomCandidate(BaseModel):
    indi_xref: str
    tree_name: str
    callsign: str
    archive_name: str
    first_year: int
    last_year: int
    state: str | None
    confidence: str   # "low" | "medium" | "high"
    note: str


class GedcomScanResult(BaseModel):
    scanned_individuals: int
    candidates: list[GedcomCandidate]
    disclaimer: str


# ---------------------------------------------------------------------------
# GEDCOM line helpers
# ---------------------------------------------------------------------------

def _ged_line(level: int, tag: str, value: str = "") -> str:
    """Emit one GEDCOM line, capping at 248 payload chars (spec limit)."""
    if value:
        line = f"{level} {tag} {value}"
    else:
        line = f"{level} {tag}"
    # Long values: split with CONT
    if len(line) <= 255:
        return line
    # Hard truncate for GEDCOM safety (real apps use CONC/CONT splits)
    head = line[:248]
    rest = line[248:]
    out = [head]
    while rest:
        out.append(f"  CONT {rest[:248]}")
        rest = rest[248:]
    return "\n".join(out)


def _ged_date(year: int) -> str:
    """Approximate GEDCOM date for a year-only known date."""
    return f"ABT {year}"


# ---------------------------------------------------------------------------
# GET /api/gedcom/{cs}
# ---------------------------------------------------------------------------

def _build_gedcom(cs: str, rows: list[sqlite3.Row]) -> str:
    """Build a GEDCOM 5.5.1 string from archive rows for one callsign."""
    lines: list[str] = []

    now_iso = datetime.utcnow().strftime("%d %b %Y").upper()

    # Header
    lines += [
        "0 HEAD",
        "1 SOUR HamCallbookArchive",
        "2 NAME U.S. Amateur Radio Callbook Archive",
        "2 VERS 1909-2003",
        "1 GEDC",
        "2 VERS 5.5.1",
        "2 FORM LINEAGE-LINKED",
        "1 CHAR UTF-8",
        f"1 DATE {now_iso}",
        "1 NOTE Generated by hamcallbook.archive — verify all facts independently.",
    ]

    # Collect holders (group rows by normalised name)
    holder_rows: dict[str, list[sqlite3.Row]] = {}
    for r in rows:
        key = (r["name"] or "").strip().upper() or "(unknown)"
        holder_rows.setdefault(key, []).append(r)

    indi_idx = 0

    # Source record
    lines += [
        "0 @S1@ SOUR",
        "1 TITL U.S. Amateur Radio Callbook Archive",
        "1 AUTH Callbook Publications / CQ Communications",
        "1 PUBL Digitised archive 1909–2003; hamcallbook.archive",
    ]

    for holder_key, h_rows in holder_rows.items():
        indi_idx += 1
        xref = f"@I{indi_idx}@"
        h_rows_sorted = sorted(h_rows, key=lambda r: r["year"])

        raw_name = h_rows_sorted[0]["name"] or holder_key
        # Try to split into given/surname (callbook format is usually "LAST FIRST" or "FIRST LAST")
        # Treat as "given" only if we can't split; genealogy software handles it
        name_gedcom = raw_name.replace("/", "").strip()
        # Wrap surname in slashes if it looks like "LAST, FIRST" or is a single token
        parts = name_gedcom.split()
        if len(parts) >= 2:
            given = " ".join(parts[1:])
            surn = parts[0].rstrip(",")
            display_name = f"{given} /{surn}/"
        else:
            display_name = f"{name_gedcom}"

        lines += [
            f"0 {xref} INDI",
            f"1 NAME {display_name}",
        ]

        prev_class: str | None = None
        prev_cs: str | None = None

        for r in h_rows_sorted:
            yr = r["year"]
            edition = r["edition"] or str(yr)
            lclass = (r["license_class"] or "").strip().upper()
            addr_parts = [
                r["address"] or "",
                r["city"] or "",
                r["state"] or "",
                r["zip"] or "",
            ]
            addr = ", ".join(p for p in addr_parts if p.strip())

            # RESI event per edition-year
            lines += [
                "1 RESI",
                f"2 DATE {_ged_date(yr)}",
            ]
            if addr.strip():
                lines.append(f"2 ADDR {addr.strip()[:248]}")
            lines += [
                "2 SOUR @S1@",
                f"3 PAGE {edition} edition, callsign {cs}",
                f"3 NOTE License class: {lclass or 'unknown'}",
            ]

            # First license event on first row
            if r is h_rows_sorted[0]:
                lines += [
                    "1 EVEN",
                    f"2 TYPE First License",
                    f"2 DATE {_ged_date(yr)}",
                    f"2 NOTE Callsign {cs} first appeared in the {edition} callbook edition.",
                    "2 SOUR @S1@",
                    f"3 PAGE {edition} edition",
                ]

            # Upgrade event on class change
            if lclass and lclass != prev_class and prev_class is not None:
                lines += [
                    "1 EVEN",
                    f"2 TYPE License Upgrade",
                    f"2 DATE {_ged_date(yr)}",
                    f"2 NOTE Upgraded from {prev_class} to {lclass} (observed in {edition} edition).",
                    "2 SOUR @S1@",
                    f"3 PAGE {edition} edition",
                ]
            prev_class = lclass or prev_class

            # Callsign-change event (only relevant if prior holder was different callsign, not applicable here)
            # We emit callsign as a custom attribute on each INDI
            if cs != prev_cs:
                lines += [
                    "1 EVEN",
                    f"2 TYPE Amateur Radio Callsign",
                    f"2 DATE {_ged_date(yr)}",
                    f"2 NOTE Callsign: {cs}",
                    "2 SOUR @S1@",
                    f"3 PAGE {edition} edition",
                ]
                prev_cs = cs

    # Trailer
    lines.append("0 TRLR")

    return "\r\n".join(lines) + "\r\n"


@router.get("/{cs}")
def get_gedcom(
    cs: str = PathParam(..., description="Callsign, case-insensitive."),
    db: sqlite3.Connection = Depends(get_db),
) -> Response:
    """Emit a GEDCOM 5.5.1 file for a callsign's archive history."""
    callsign = normalize_callsign(cs)

    cur = db.execute(
        """
        SELECT year, edition, name, address, city, state, zip, license_class
        FROM   entries
        WHERE  callsign = ?
        ORDER  BY year ASC
        """,
        (callsign,),
    )
    rows = cur.fetchall()
    if not rows:
        raise HTTPException(status_code=404, detail=f"callsign not found: {callsign}")

    ged_text = _build_gedcom(callsign, rows)

    return Response(
        content=ged_text.encode("utf-8"),
        media_type="text/plain; charset=utf-8",
        headers={
            "Content-Disposition": f'attachment; filename="{callsign}.ged"',
            "Cache-Control": "no-store",
        },
    )


# ---------------------------------------------------------------------------
# POST /api/gedcom/scan
# ---------------------------------------------------------------------------

# Parse INDI name lines from a GEDCOM upload
_INDI_RE = re.compile(r"^0\s+(@\S+@)\s+INDI", re.MULTILINE)
_NAME_RE = re.compile(r"^1\s+NAME\s+(.+)$", re.MULTILINE)
_BIRTH_RE = re.compile(r"^2\s+DATE\s+.*?(\d{4})", re.MULTILINE)


def _extract_individuals(text: str) -> list[dict[str, Any]]:
    """Parse GEDCOM text -> list of {xref, name, birth_year?}."""
    individuals: list[dict[str, Any]] = []
    # Split on INDI records
    blocks = re.split(r"(?=^0\s+@\S+@\s+INDI)", text, flags=re.MULTILINE)
    for block in blocks:
        m_indi = _INDI_RE.match(block.strip())
        if not m_indi:
            continue
        xref = m_indi.group(1)
        m_name = _NAME_RE.search(block)
        if not m_name:
            continue
        raw_name = m_name.group(1).strip()
        # GEDCOM name format: "Given /SURNAME/ Suffix" — strip slashes
        clean_name = re.sub(r"/([^/]*)/", r"\1", raw_name).strip()
        # Birth year: look for BIRT event then DATE
        birth_year: int | None = None
        birt_match = re.search(r"1\s+BIRT.*?(?=^1\s|\Z)", block, re.DOTALL | re.MULTILINE)
        if birt_match:
            yr_m = _BIRTH_RE.search(birt_match.group(0))
            if yr_m:
                birth_year = int(yr_m.group(1))
        # State: RESI ADDR lines
        state_hints: list[str] = []
        for addr_m in re.finditer(r"2\s+ADDR\s+(.+)", block):
            # Last two uppercase alpha tokens of an address line are often state abbreviations
            tokens = addr_m.group(1).split()
            for tok in reversed(tokens):
                tok_clean = tok.strip(",.").upper()
                if len(tok_clean) == 2 and tok_clean.isalpha():
                    state_hints.append(tok_clean)
                    break
        individuals.append(
            {
                "xref": xref,
                "name": clean_name,
                "birth_year": birth_year,
                "state_hints": list(set(state_hints)),
            }
        )
    return individuals


def _phonetic_key_for_name(name: str) -> list[str]:
    """Return candidate phonetic keys for a person name string."""
    # Import helpers from people route (same logic)
    try:
        import jellyfish  # type: ignore

        def _meta(w: str) -> str:
            return jellyfish.metaphone(w) or w[:4].upper()
    except ImportError:
        def _meta(w: str) -> str:  # type: ignore[misc]
            return w[:4].upper()

    tokens = [t for t in re.findall(r"[A-Za-z]+", name) if len(t) > 1]
    if not tokens:
        return []
    keys = []
    # Full name key (first + last)
    if len(tokens) >= 2:
        keys.append(f"{_meta(tokens[0])}|{_meta(tokens[-1])}")
    # Surname-only
    keys.append(_meta(tokens[-1]))
    # First-only
    keys.append(_meta(tokens[0]))
    return list(dict.fromkeys(keys))  # dedup, preserve order


def _confidence(name_match: bool, state_match: bool, era_match: bool) -> str:
    score = sum([name_match, state_match, era_match])
    if score == 3:
        return "high"
    if score == 2:
        return "medium"
    return "low"


@router.post("/scan", response_model=GedcomScanResult)
async def scan_gedcom(
    file: UploadFile = File(..., description="GEDCOM 5.5.1 family-tree file (max 5 MB)."),
) -> GedcomScanResult:
    """
    Upload a family-tree GEDCOM.  Match individuals against the callbook
    phonetic index.  Stateless — file processed in memory, never stored.
    Returns conservative candidate hits; all require manual verification.
    """
    raw = await file.read(_GEDCOM_MAX_BYTES + 1)
    if len(raw) > _GEDCOM_MAX_BYTES:
        raise HTTPException(
            status_code=413,
            detail="GEDCOM file exceeds 5 MB limit.",
        )

    try:
        text = raw.decode("utf-8", errors="replace")
    except Exception:
        raise HTTPException(status_code=400, detail="Could not decode GEDCOM file as UTF-8.")

    individuals = _extract_individuals(text)
    if not individuals:
        raise HTTPException(status_code=400, detail="No INDI records found in uploaded GEDCOM.")

    # Ensure phonetic index is loaded
    _phonetic_index.ensure_loaded()

    candidates: list[GedcomCandidate] = []

    for person in individuals[:500]:  # cap at 500 individuals per upload
        name = person["name"]
        birth_year: int | None = person["birth_year"]
        state_hints: list[str] = person["state_hints"]

        if not name or len(name) < 2:
            continue

        pkeys = _phonetic_key_for_name(name)

        seen_callsigns: set[str] = set()

        for pkey in pkeys:
            posting = _phonetic_index.lookup(pkey)
            if not posting:
                continue

            # posting shape: {t: [[callsign, year, name, state], ...], p: ...}
            entries: list[Any] = posting.get("t", [])

            for entry in entries[:200]:  # limit per key
                if len(entry) < 4:
                    continue
                e_callsign: str = entry[0] if entry[0] else ""
                e_year: int = int(entry[1]) if entry[1] else 0
                e_name: str = entry[2] if entry[2] else ""
                e_state: str = (entry[3] or "").strip().upper()

                if not e_callsign or e_callsign in seen_callsigns:
                    continue

                # Era plausibility: birth_year within +-40 yrs of first license
                era_ok = True
                if birth_year and e_year:
                    age_at_license = e_year - birth_year
                    era_ok = 10 <= age_at_license <= 80  # plausible licensing age range

                # State match
                state_ok = not state_hints or e_state in state_hints

                conf = _confidence(True, state_ok, era_ok)

                # Only include medium/high confidence matches
                if conf == "low" and not state_ok and not era_ok:
                    continue

                # Build a human-readable note
                note_parts = [
                    f"Your tree individual '{name}' may match callbook operator "
                    f"'{e_name}' who held {e_callsign} in {e_year}",
                ]
                if e_state:
                    note_parts.append(f"(state: {e_state})")
                note_parts.append("— verify independently before drawing conclusions.")
                note = " ".join(note_parts)

                seen_callsigns.add(e_callsign)

                # Find first and last year for this callsign in the index
                # (approximate: use e_year as both; fuller lookup would hit DB)
                candidates.append(
                    GedcomCandidate(
                        indi_xref=person["xref"],
                        tree_name=name,
                        callsign=e_callsign,
                        archive_name=e_name,
                        first_year=e_year,
                        last_year=e_year,
                        state=e_state or None,
                        confidence=conf,
                        note=note,
                    )
                )

                if len(candidates) >= 200:
                    break
            if len(candidates) >= 200:
                break

    # Sort: high > medium > low, then by confidence label
    _conf_order = {"high": 0, "medium": 1, "low": 2}
    candidates.sort(key=lambda c: _conf_order.get(c.confidence, 9))

    return GedcomScanResult(
        scanned_individuals=len(individuals),
        candidates=candidates[:100],  # return at most 100
        disclaimer=(
            "These are candidate matches only — phonetic name similarity does not confirm identity. "
            "Always verify against primary sources (FCC ULS, QSL cards, obituaries, family records) "
            "before including in a genealogical record."
        ),
    )
